language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - sudo apt-get update
  - sudo apt-get install csstidy libxml2-dev libxslt-dev
install:
  - pip install -e . --use-deprecated=legacy-resolver
  - pip install -r requirements/tests.txt Django==$DJANGO --use-deprecated=legacy-resolver
script:
  - make test
env:
  - DJANGO=1.7
branches:
  only:
    - develop
notifications:
  irc: "irc.freenode.org#django-compressor"
